<a href="https://colab.research.google.com/github/Darsana33/datascience_lab/blob/main/4_1_22_DarsanaNa%C3%AFve_Bayes_Algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Aim: Program to implement Naïve Bayes Algorithm using any standard dataset
available in the public domain and find the accuracy of the algorithm


Short notes: Naive Bayes

Bayes’ Theorem provides a way that we can calculate the probability of a piece of data belonging to a given class, given our prior knowledge. Bayes’ Theorem is stated as:

P(class|data) = (P(data|class) * P(class)) / P(data)

Where P(class|data) is the probability of class given the provided data.

We are using Iris Dataset. The Iris Flower Dataset involves predicting the flower species given measurements of iris flowers.

It is a multiclass classification problem. The number of observations for each class is balanced. There are 150 observations with 4 input variables and 1 output variable. The variable names are as follows:

Sepal length in cm.

Sepal width in cm.

Petal length in cm.

Petal width in cm., and

Class.

Algorithm:

Step 1: Separate By Class.

Step 2: Summarize Dataset.

Step 3: Summarize Data By Class.

Step 4: Gaussian Probability Density Function.

Step 5: Class Probabilities.

In [1]:
#Import Modules
import numpy as np
import matplotlib.pyplot as plt
from sklearn import neighbors, datasets, preprocessing
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score


#Load iris dataset & do train_test_split 
iris=datasets.load_iris()
x,y=iris.data[:,:],iris.target
x_train,x_test,y_train,y_test=train_test_split(x,y,stratify=y,random_state=20,train_size=.8)


In [2]:
#Feature Scaling
scaler=preprocessing.StandardScaler().fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)
x_train

array([[-0.02627732, -1.00810966,  0.13128182,  0.00996   ],
       [-0.87523698,  1.10598438, -1.34741591, -1.31804007],
       [-0.75395703,  1.10598438, -1.29054292, -1.31804007],
       [-1.11779688,  1.34088372, -1.34741591, -1.45084008],
       [-0.51139713,  2.04558174, -1.4042889 , -1.05244006],
       [-0.26883722, -0.53831098,  0.64313872,  1.07236006],
       [-0.99651693, -1.71280767, -0.26682911, -0.25564001],
       [ 0.94396229, -0.30341164,  0.47251976,  0.14276001],
       [-0.99651693,  0.63618571, -1.34741591, -1.31804007],
       [ 0.58012243, -1.243009  ,  0.70001171,  0.93956005],
       [ 0.58012243,  0.63618571,  1.26874161,  1.73636009],
       [ 2.27804175, -0.53831098,  1.66685254,  1.07236006],
       [-0.39011718, -1.47790834,  0.01753584, -0.12284001],
       [-1.48163674,  0.40128637, -1.34741591, -1.31804007],
       [-1.72419664,  0.40128637, -1.4042889 , -1.31804007],
       [-0.87523698,  0.87108505, -1.29054292, -1.31804007],
       [-0.87523698, -1.

In this step, we introduce the class GaussianNB that is used from the sklearn.naive_bayes library. Here, we have used a Gaussian model, there are several other models such as Bernoulli, Categorical and Multinomial. Here, we assign the GaussianNB class to the variable classifier and fit the X_train and y_train values to it for training purpose.

In [3]:
#Implement Naive Bayes
from sklearn.naive_bayes  import GaussianNB
darsana=GaussianNB()
darsana.fit(x_train,y_train)

GaussianNB()

In [6]:
#Predict the values for test data 
y_test_pred=darsana.predict(x_test) 

# Display accuracy score & display confusion matrix & classification report
print(accuracy_score(y_test,y_test_pred))
print("confusion matrix")
print(confusion_matrix(y_test,y_test_pred))
print("classification report")
print(classification_report(y_test,y_test_pred))


1.0
confusion matrix
[[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]
classification report
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        10
           2       1.00      1.00      1.00        10

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [7]:
#bernoulli
from sklearn.naive_bayes  import BernoulliNB
darsana= BernoulliNB()
darsana.fit(x_train,y_train)
y_test_pred=darsana.predict(x_test)
print(accuracy_score(y_test,y_test_pred))
print("confusion matrix")
print(confusion_matrix(y_test,y_test_pred))
print("classification report")
print(classification_report(y_test,y_test_pred))


0.7
confusion matrix
[[10  0  0]
 [ 2  2  6]
 [ 0  1  9]]
classification report
              precision    recall  f1-score   support

           0       0.83      1.00      0.91        10
           1       0.67      0.20      0.31        10
           2       0.60      0.90      0.72        10

    accuracy                           0.70        30
   macro avg       0.70      0.70      0.65        30
weighted avg       0.70      0.70      0.65        30



From the above confusion matrix, we infer that, out of 45 test set data, 44 were correctly classified and only 1 was incorrectly classified. This gives us a high accuracy of 97.7%.