<a href="https://colab.research.google.com/github/Darsana33/datascience_lab/blob/main/Darsana_20CO_1_Matrix_Operations_%26_Creating_a_dataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  Matrix Operations

#### Matrices

In [3]:
# Create a matrix using the 'matrix()' function of the 'numpy' module.
import numpy as np
m1=np.matrix('1 2 3;4 5 6')
m1

matrix([[1, 2, 3],
        [4, 5, 6]])

In [4]:
# Convert a nested Python list into a matrix using the 'matrix()' function of the 'numpy' module.
m2=np.matrix([[2,4],[6,8],[10,12]])
m2

matrix([[ 2,  4],
        [ 6,  8],
        [10, 12]])

#### Matrix Multiplication



$$\begin{bmatrix} 8 & 7 \\ 3	& -5	\\\end{bmatrix} \begin{bmatrix} 3 \\ 2 \\\end{bmatrix}$$

To multiply two matrices, you have to use the `matmul()` function of the `numpy` module. It takes two matrices to be multiplied as inputs and returns a new matrix.

In [5]:
# Multiplication of the above two matrices.
m1=np.matrix([[8,7],[3,-5]])
m2=np.matrix('3 ;2')
mul=np.matmul(m1,m2)
mul

matrix([[38],
        [-1]])

**Note:** The number of columns in the first matrix should be the same as the number of rows in the second matrix. Otherwise, you will get `ValueError`

####  Identity Matrix

In [7]:
# Create an identity matrix of the dimension 5 and of 'int' type.
iden=np.identity(5,dtype=int)
iden

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

Now let's multiply a square matrix with an identity matrix of the same dimension (say 3).

In [8]:
# Multiply a square matrix with an identity matrix of the same dimension.
mtx=np.matrix('2 3 4;1 2 3;5 6 7')
iden=np.identity(3,dtype=int)
mul=np.matmul(mtx,iden)
mul

matrix([[2, 3, 4],
        [1, 2, 3],
        [5, 6, 7]])

----

####  Multiplicative Inverse of a Matrix^


Eg. let $A$ be a matrix of dimension $3$

$$A = \begin{bmatrix} 1 & 3 & 3 \\ 1 & 4 & 3 \\ 1 & 3 & 4 \\\end{bmatrix}$$

Then its inverse is

$$A^{-1} = \begin{bmatrix} 7 & - 3 & -3 \\ -1 & 1 & 0 \\ -1 & 0 & 1 \\\end{bmatrix}$$

Both $A$ and $A^{-1}$ have the same dimension.

If you multiply the matrix $A$ with its inverse, you should get the identity matrix of dimension $3$.

$$A^{-1} A = \begin{bmatrix} 7 & - 3 & -3 \\ -1 & 1 & 0 \\ -1 & 0 & 1 \\\end{bmatrix} \begin{bmatrix} 1 & 3 & 3 \\ 1 & 4 & 3 \\ 1 & 3 & 4 \\\end{bmatrix}$$

$$\Rightarrow A^{-1}A = \begin{bmatrix} 7 \times 1 - 3 \times 1 -3 \times 1 &7 \times 3 - 3 \times 4 -3 \times 3 & 7 \times 3 - 3 \times 3 - 3 \times 4 \\ -1 \times 1 + 1 \times 1 + 0 \times 1 & -1 \times 3 + 1 \times 4 + 0 \times 3 & -1 \times 3 + 1 \times 3 + 0 \times 4 \\ -1 \times 1 + 0 \times 1 + 1 \times 1 & -1 \times 3 + 0 \times 4 + 1 \times 3 & -1 \times 3 + 0 \times 3 + 1 \times 4 \\\end{bmatrix}$$

$$\Rightarrow A^{-1}A = \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \\\end{bmatrix}$$


In [9]:
#Multiply the above matrix with its inverse.
m1=np.matrix('1 3 3;1 4 3;1 3 4')
inv=np.linalg.inv(m1)
mul=np.matmul(m1,inv)
mul

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

#### Determinant of a Matrix^^


$$X = \begin{bmatrix} 8 & 7 \\ 3	& -5 \\\end{bmatrix}$$

 To calculate the determinant value of a square matrix, use the `linalg.det()` function of the `numpy` module.

**Syntax:** `np.linalg.det(a)`

where `a` is some square matrix.

In [10]:
# Calculate the determinant of the matrix X.
x=np.matrix('8 7 ; 3 -5')
det=np.linalg.det(x)
det

-60.99999999999995

Let's calculate the determinant of the matrix

$$A = \begin{bmatrix} 1 & 3 & 3 \\ 1 & 4 & 3 \\ 1 & 3 & 4 \\\end{bmatrix}$$

using Python.

In [11]:
#Calculate the determinant of the above matrix A.
A=np.matrix('1 3 3;1 4 3;1 3 4')
det=np.linalg.det(A)
det

1.0

In [12]:
# Calculate the inverse of the above matrix A.
A=np.matrix('1 3 3;1 4 3;1 3 4')
inv=np.linalg.inv(A)
inv

matrix([[ 7., -3., -3.],
        [-1.,  1.,  0.],
        [-1.,  0.,  1.]])

In [22]:
#Create a dictionary to store weatherdata and convert it to a dtaframe
import pandas as pd
weather={'day':['20/11/21','21/11/21','22/44/21','23/11/21','24/11/21','25/11/21'],
         'city':['kochi','athani','tripunithura','chottanikara','piravom','thiruvaniyoor'],
         'temparature':[30,27,29,26,33,32],
         'windspeed':[50,60,55,65,67,65]}
df=pd.DataFrame(weather)
# Display the first five rows of dataframe
df.head()



day          city  temparature  windspeed
0  20/11/21         kochi           30         50
1  21/11/21        athani           27         60
2  22/44/21  tripunithura           29         55
3  23/11/21  chottanikara           26         65
4  24/11/21       piravom           33         67

In [23]:
#Display the last five rows of dataframe

df.tail()

day           city  temparature  windspeed
1  21/11/21         athani           27         60
2  22/44/21   tripunithura           29         55
3  23/11/21   chottanikara           26         65
4  24/11/21        piravom           33         67
5  25/11/21  thiruvaniyoor           32         65